using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace api.Models;

/// <summary>
/// A restaurant stored in the "restaurants" table, to which ratings are attached.
/// </summary>
[Table("restaurants")]
public class Restaurant : BaseModel
{
    /// <summary>
    /// Database identifier, generated by the database on insert.
    /// </summary>
    [PrimaryKey("id", false)]
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// OpenStreetMap identifier ("{osm_type}{osm_id}", e.g. "N5287924742"); unique, null for restaurants not linked to OSM.
    /// </summary>
    [Column("osm_id")]
    public string? OsmId { get; set; }

    /// <summary>
    /// Name of the restaurant.
    /// </summary>
    [Column("name")]
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Type of cuisine (e.g. "Italian").
    /// </summary>
    [Column("cuisine")]
    public string Cuisine { get; set; } = string.Empty;

    /// <summary>
    /// Emoji displayed next to the restaurant name.
    /// </summary>
    [Column("emoji")]
    public string Emoji { get; set; } = string.Empty;

    /// <summary>
    /// Postal address.
    /// </summary>
    [Column("address")]
    public string Address { get; set; } = string.Empty;

    /// <summary>
    /// Free text description.
    /// </summary>
    [Column("description")]
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Latitude in degrees, when known.
    /// </summary>
    [Column("lat")]
    public double? Lat { get; set; }

    /// <summary>
    /// Longitude in degrees, when known.
    /// </summary>
    [Column("lng")]
    public double? Lng { get; set; }
}
