using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;

namespace api.Models;

/// <summary>
/// A user's collection of restaurants, stored in the "tierlists" table. Its restaurants are in "tierlist_restaurant".
/// </summary>
[Table("tierlists")]
public class Tierlist : BaseModel
{
    /// <summary>
    /// Database identifier, generated by the database on insert.
    /// </summary>
    [PrimaryKey("id", false)]
    public long Id { get; set; }

    /// <summary>
    /// Supabase Auth identifier of the user who created the tierlist (nullable column, always set by the API).
    /// </summary>
    [Column("id_user")]
    public string? UserId { get; set; }

    /// <summary>
    /// Name of the tierlist (nullable column, always set by the API).
    /// </summary>
    [Column("name")]
    public string? Name { get; set; }

    /// <summary>
    /// Free text description, null when the user gave none.
    /// </summary>
    [Column("description")]
    public string? Description { get; set; }

    /// <summary>
    /// Emoji used as the tierlist picture (nullable column, always set by the API).
    /// </summary>
    [Column("emoji")]
    public string? Emoji { get; set; }

    /// <summary>
    /// True when the user pinned the tierlist to its profile; null is read as not pinned.
    /// </summary>
    [Column("pinned")]
    public bool? Pinned { get; set; }

    /// <summary>
    /// Creation date, set by the database on insert (never sent by the API).
    /// </summary>
    [Column("created_at", ignoreOnInsert: true, ignoreOnUpdate: true)]
    public DateTime CreatedAt { get; set; }
}
