using api.Common;
using api.Models;

namespace api.Services;

/// <summary>
/// Saves and reads the tierlists users create.
/// </summary>
public interface ITierlistService
{
    /// <summary>
    /// Creates a tierlist of <paramref name="userId"/>, without restaurants.
    /// </summary>
    /// <param name="userId">Supabase Auth id of the user creating the tierlist.</param>
    /// <param name="request">Emoji, name, description and pinned flag, already validated.</param>
    /// <param name="cancellationToken">Cancels the database query.</param>
    /// <returns>The created tierlist, with the id and creation date generated by the database.</returns>
    Task<Result<TierlistResponse>> CreateAsync(string userId, CreateTierlistRequest request, CancellationToken cancellationToken);

    /// <summary>
    /// Returns every tierlist of <paramref name="userId"/>, with its restaurants, most recently created first.
    /// </summary>
    /// <param name="userId">Supabase Auth id of the user.</param>
    /// <param name="cancellationToken">Cancels the database queries.</param>
    /// <returns>The tierlists, or a NotFound failure when <paramref name="userId"/> is not a user id (uuid).</returns>
    Task<Result<IReadOnlyList<TierlistResponse>>> GetByUserAsync(string userId, CancellationToken cancellationToken);

    /// <summary>
    /// Returns a tierlist with its restaurants.
    /// </summary>
    /// <param name="id">Database id of the tierlist.</param>
    /// <param name="cancellationToken">Cancels the database queries.</param>
    /// <returns>The tierlist, or a NotFound failure when it does not exist.</returns>
    Task<Result<TierlistResponse>> GetByIdAsync(long id, CancellationToken cancellationToken);
}
