using api.Common;
using api.Models;

namespace api.Services;

/// <summary>
/// Saves the tierlists users create.
/// </summary>
public interface ITierlistService
{
    /// <summary>
    /// Creates a tierlist of <paramref name="userId"/>, without restaurants.
    /// </summary>
    /// <param name="userId">Supabase Auth id of the user creating the tierlist.</param>
    /// <param name="request">Emoji, name, description and pinned flag, already validated.</param>
    /// <param name="cancellationToken">Cancels the database query.</param>
    /// <returns>The created tierlist, with the id and creation date generated by the database.</returns>
    Task<Result<TierlistResponse>> CreateAsync(string userId, CreateTierlistRequest request, CancellationToken cancellationToken);
}
