using api.Common;
using api.Models;
using Supabase.Postgrest.Responses;

namespace api.Services;

/// <summary>
/// Saves the tierlists users create in the "tierlists" table.
/// </summary>
/// <param name="supabase">Client of the Supabase database.</param>
public class TierlistService(Supabase.Client supabase) : ITierlistService
{
    /// <summary>
    /// Client of the Supabase database.
    /// </summary>
    private readonly Supabase.Client _supabase = supabase ?? throw new ArgumentNullException(nameof(supabase));

    /// <inheritdoc />
    public async Task<Result<TierlistResponse>> CreateAsync(string userId, CreateTierlistRequest request, CancellationToken cancellationToken)
    {
        ModeledResponse<Tierlist> inserted = await _supabase.From<Tierlist>()
            .Insert(request.ToTierlist(userId), cancellationToken: cancellationToken);

        // The inserted row is returned with the id and creation date generated by the database
        Tierlist? tierlist = inserted.Models.FirstOrDefault();
        return tierlist is null
            ? Result<TierlistResponse>.Failure(new Error(ErrorType.Unavailable, "The tierlist could not be created."))
            : Result<TierlistResponse>.Success(TierlistResponse.From(tierlist));
    }
}
